export const jobTitles = [
    // The comprehensive list of job titles you provided
    "Software Developer", "Software Engineer", "Senior Software Engineer", "Junior Software Engineer", "Full Stack Developer", "Front End Developer",
    "Back End Developer", "Web Developer", "Mobile Developer", "iOS Developer", "Android Developer", "DevOps Engineer", "Cloud Engineer", "Systems Engineer",
    "Network Engineer", "Security Engineer", "Data Engineer", "Data Scientist", "Machine Learning Engineer", "AI Engineer", "Database Administrator",
    "Database Developer", "Big Data Engineer", "Business Intelligence Developer", "Business Analyst", "Systems Analyst", "Application Support Analyst",
    "Technical Support Engineer", "Help Desk Technician", "IT Support Specialist", "QA Engineer", "QA Tester", "Automation Tester", "Test Engineer",
    "Test Analyst", "Technical Writer", "UX Designer", "UI Designer", "Product Manager", "Project Manager", "Scrum Master", "Technical Lead", "Engineering Manager",
    "CTO", "CIO", "IT Manager", "IT Director", "Program Manager", "Release Manager", "Configuration Manager", "Build Engineer", "Site Reliability Engineer",
    "Solutions Architect", "Enterprise Architect", "Technical Architect", "Information Architect", "Software Architect", "Platform Engineer", "Infrastructure Engineer",
    "Integration Engineer", "Firmware Engineer", "Embedded Systems Engineer", "Control Systems Engineer", "Robotics Engineer", "Game Developer", "Game Designer",
    "Game Programmer", "Virtual Reality Developer", "Augmented Reality Developer", "Blockchain Developer", "Smart Contract Developer", "Cryptocurrency Developer",
    "Quantum Computing Developer", "Technical Account Manager", "Sales Engineer", "Pre-Sales Engineer", "Post-Sales Engineer", "Customer Success Engineer",
    "Customer Support Engineer", "Field Service Engineer", "Professional Services Engineer", "Consulting Engineer", "Solutions Engineer", "Network Administrator",
    "Systems Administrator", "Cloud Administrator", "Storage Administrator", "Virtualization Engineer", "Infrastructure Architect", "IT Consultant", "IT Auditor",
    "IT Security Consultant", "Penetration Tester", "Ethical Hacker", "Cybersecurity Analyst", "Incident Response Analyst", "Forensic Analyst", "Security Operations Center (SOC) Analyst",
    "Vulnerability Analyst", "Security Administrator", "Security Consultant", "Information Security Analyst", "Information Security Manager", "Information Security Officer",
    "Chief Information Security Officer (CISO)", "Risk Analyst", "Compliance Analyst", "Regulatory Affairs Specialist", "Technical Program Manager", "Technical Project Manager",
    "Product Owner", "Release Engineer", "Site Operations Engineer", "Operations Engineer", "Deployment Engineer", "Integration Specialist", "ERP Specialist",
    "CRM Specialist", "HRIS Specialist", "E-commerce Specialist", "Content Management Specialist", "Digital Marketing Specialist", "SEO Specialist",
    "Social Media Specialist", "Web Analytics Specialist", "Marketing Automation Specialist", "Cloud Solutions Engineer", "Cloud Solutions Architect",
    "Cloud Solutions Consultant", "Cloud Platform Engineer", "Cloud Infrastructure Engineer", "Cloud Security Engineer", "Cloud Network Engineer", "Cloud DevOps Engineer",
    "Cloud Operations Engineer", "Data Analytics Engineer", "Data Visualization Engineer", "Data Warehouse Engineer", "Big Data Architect", "Big Data Consultant",
    "Data Migration Engineer", "Data Integration Engineer", "AI Research Scientist", "AI Product Manager", "AI Solutions Architect", "AI Consultant", "Machine Learning Scientist",
    "NLP Engineer", "Computer Vision Engineer", "Deep Learning Engineer", "Research Scientist", "Research Engineer", "Research Associate", "Academic Researcher",
    "Postdoctoral Researcher", "University Lecturer", "Adjunct Professor", "Tenure-Track Professor", "Technical Trainer", "Technical Instructor", "Technical Evangelist",
    "Developer Advocate", "Developer Evangelist", "Community Manager", "Open Source Developer", "Open Source Advocate", "Open Source Maintainer", "Freelance Developer",
    "Independent Consultant", "Technical Consultant", "IT Trainer"
  ];
  